- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - build-release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
