- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-cover:
            voting: false
    gate:
      jobs:
        - build-openstack-releasenotes
