- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-lower-constraints
        - build-openstack-releasenotes
        - openstack-tox-cover:
            voting: false

    gate:
      jobs:
        - openstack-tox-lower-constraints
        - build-openstack-releasenotes
